---
title: "Homework 6"
author: "EEMB 174-274"
output: pdf_document
header-includes:
  - \usepackage{color}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rethinking)
#source("../helper.R")
```
# Bayesian Statistical Modeling Winter 2024
# Homework, Week 8

*When is homework due?* This assignment is due on Monday, 3/4/2024. 


Complete these problems from the end of chapter 

## 9E4


## 9E5


## 9E6


# chapter 10
Figure 10.6 explains the relationships between the 5 Maximum Entropy probability distributions. The book describes scenarios in which each of these distributions could be thought of as the "least assumption" way to describe the data. Another way of deriving these distributions is by considering a random process where individuals are all considered to be facing the same odds of each outcome. 

## Process producing the binomial:
Describe how some biological process of interest to you (population size following climate change, reproductive outputs under different experimental conditions, survivorship, outcomes of an experimental treatment, etc.) could result in a Binomial distribution:

## Process producing the Poisson:
Describe how some biological process of interest to you (population size following climate change, reproductive outputs under different experimental conditions, survivorship, outcomes of an experimental treatment, etc.) could result in a Poisson distribution:

